services:
  - type: web
    name: travian-farming-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
buildCommand: "cd madara-farming-bot && pip install -r requirements.txt"
startCommand: "cd madara-farming-bot && uvicorn backend.main:app --host 0.0.0.0 --port 10000"
